extends RefCounted
static func say(a: Array, who: String, text: String):
 var lines := text.split("\n")
 for start in range(0,lines.size(),3): a.append({"kind":"say","who":who,"text":"\n".join(lines.slice(start,mini(start+3,lines.size())))})
static func deal(a: Array, player: Array, enemy: Array): a.append({"kind":"deal","player":player,"enemy":enemy})
static func wait_for(a: Array, action: String): a.append({"kind":"wait","action":action})
static func draw(a: Array, actor: String, value: int): a.append({"kind":"draw","actor":actor,"value":value})
static func reveal(a: Array): a.append({"kind":"reveal"})
static func effect(a: Array, text: String, type: String = "peak", seconds: float = 1.1, extra: Dictionary = {}):
 var entry := {"kind":"effect","text":text,"effect":type,"time":seconds};entry.merge(extra);a.append(entry)
static func score(a: Array, value: Array, round_number: int, text: String): a.append({"kind":"score","value":value,"round":round_number,"text":text})
static func build(mode: String) -> Array:
 var a: Array = []
 if mode == "junior":
  say(a,"小師妹","师兄，来学问剑吧。\n先看看规矩，再陪我走五局。")
  deal(a,[10,8],[10,7]);say(a,"小師妹","師兄，先陪我試一手。\n又不收你靈石，別一臉要去赴死的樣子。")
  say(a,"小師妹","你看，十八。已經不小了。\n咱們比誰更接近二十一，超過就爆了，叫『勢滿而崩』。\n先按『收劍守勢』，看看我能不能追上你。")
  wait_for(a,"stand");reveal(a);score(a,[1,0],1,"十八對十七 · 這局你贏")
  say(a,"小師妹","……十七。差你一點。\n先別笑，還有下一局呢。")
  deal(a,[10,6],[10,8]);say(a,"小師妹","這回十六。你是不是也有點想再拿一枚？\n按『再出一劍』試試。\n先說好，我可沒保證下一枚是什麼。")
  wait_for(a,"draw");draw(a,"player",4);say(a,"小師妹","四，湊成二十了。\n可以了可以了，再拿我都替你捏把汗。\n收劍，把難題留給我吧。")
  wait_for(a,"stand");reveal(a);score(a,[2,0],2,"二十對十八 · 這局你贏")
  deal(a,[7,5],[10,7]);say(a,"小師妹","才十二。\n這手要不要再拿？來，試一枚。")
  wait_for(a,"draw");draw(a,"player",10);effect(a,"勢滿而崩 · 二十二","bust")
  say(a,"小師妹","……二十二。\n好吧，這回算我慫恿你的。\n可別學會出劍，就忘了還能收劍啊。")
  say(a,"小師妹","不用每次都湊到二十一。\n你早點停，換我去追；要是我先爆了，贏的還是你。\n所以我剛才讓你拿，你也不用次次都聽。")
  score(a,[2,1],3,"這局小師妹贏")
  deal(a,[10,8],[10,1]);say(a,"小師妹","欸，這回輪到我拿好東西了。\n看這枚『靈』，先別急著替我算。")
  wait_for(a,"stand");reveal(a);effect(a,"【靈】可作一或十一","natural",1.1,{"enemy":10})
  effect(a,"靈 → 十一","natural",.8,{"enemy":21});effect(a,"天命一劍\n開局劍勢圓滿 · 二十一","natural",1.3)
  say(a,"小師妹","靈印能算一，也能算十一。配上我這枚十，正好二十一。\n要是算十一會爆，它就退回一。\n這可不是我耍賴，你拿到也一樣。")
  score(a,[2,2],4,"這局小師妹贏")
  deal(a,[5,6],[10,8]);say(a,"小師妹","最後一局。你這起手十一，倒是很會挑時候。\n起手十或十一，可以用『孤注一劍』：只補一枚，然後必須收劍。\n贏算兩籌，輸也算兩籌。敢不敢試一次？")
  wait_for(a,"double");effect(a,"孤注一劍","double",.55);draw(a,"player",10);effect(a,"一劍定局 · 二十一","peak",1.2);reveal(a)
  score(a,[4,2],5,"孤注一劍 · 這局贏兩籌")
  say(a,"小師妹","……還真讓你拿到十了。\n行，四比二，這場算你贏。\n剛學會就贏教你的人，不太給面子吧？")
  say(a,"小師妹","以後想玩就來找我，不收你的靈石。\n至於外面那些劍帖，先看清彩頭和輸了要付什麼，再接。\n別到時候輸光了，回來說是我教的。")
 else:
  say(a,"大師姐","今日陪你走五局。\n看清藏锋，也看清每一剑的进退。")
  deal(a,[10,6],[6,1]);say(a,"你（心想）","十六，不算大。\n但她明牌只有六，很容易自己把劍勢逼爆。\n這時候沒必要跟她一起冒險。")
  wait_for(a,"stand");say(a,"你","我不出了。\n我這牌，不小。\n該你了。")
  say(a,"你（心想）","拿吧。\n最好直接爆掉。")
  say(a,"大師姐","是嗎？");effect(a,"神識探查\n你的藏鋒被看穿","probe",2.8)
  say(a,"大師姐","神識探查。\n到了築基三層，有些藏鋒，就藏不住了。")
  reveal(a);effect(a,"六 + 靈（十一）= 十七","natural")
  say(a,"大師姐","十七。\n確實不大。");score(a,[0,1],1,"這局大師姐贏")
  deal(a,[10,9],[7,5]);wait_for(a,"stand");reveal(a);draw(a,"enemy",10);effect(a,"勢滿而崩 · 二十二","bust",.8)
  say(a,"你","我上次也是這樣爆的。")
  effect(a,"劍罡護體 · 二十二 → 二十","shield",3.4,{"enemy":20})
  say(a,"你","……二十二還能救回來？")
  say(a,"大師姐","築基四層。\n劍勢失控之前，強行把它穩回來。\n二十。\n剛好比你高一點。")
  score(a,[0,2],2,"這局大師姐贏")
  deal(a,[10,10],[5,6]);wait_for(a,"stand");reveal(a)
  say(a,"你","二十。\n我不信你下一張還能剛好拿到十。")
  say(a,"大師姐","不用剛好。")
  effect(a,"孤注一劍 · 天命一劍","double");draw(a,"enemy",10);effect(a,"一劍定局 · 二十一","destiny",3.0)
  say(a,"你","……");say(a,"大師姐","築基五層。\n第一次孤注一劍時，可以把劍勢直接推到21。")
  say(a,"你","這叫問劍？");say(a,"大師姐","這叫修為。");score(a,[0,4],3,"孤注一劍 · 大師姐贏兩籌")
  deal(a,[7,6],[8,6]);say(a,"大師姐","這一局，我不看你的藏鋒。")
  say(a,"你","總算肯正常玩了？");wait_for(a,"stand");say(a,"你","十三。\n我不出了。")
  effect(a,"窺天一線 · 下一位修士即將抽到的牌是八","foresight",3.2);say(a,"大師姐","下一枚是八。\n不拿。")
  say(a,"你","……你怎麼知道是八？");say(a,"大師姐","築基六層。\n出劍以前，先看一眼下一步。")
  reveal(a);score(a,[0,5],4,"十四對十三 · 這局大師姐贏")
  deal(a,[8],[10,9]);say(a,"你","……還真是八。");say(a,"大師姐","現在信了？")
  draw(a,"player",3);wait_for(a,"draw");draw(a,"player",10);effect(a,"劍勢圓滿 · 二十一","peak",1.4);reveal(a)
  score(a,[1,5],5,"這局你贏 · 一勝")
  say(a,"你","二十一。\n五局贏一局就算我贏。\n大師姐，這可是你自己說的。")
  say(a,"大師姐","嗯。\n可惜了。");effect(a,"……","quiet",1.0)
  effect(a,"逆轉光陰","rewind",3.2,{"clear":true,"score":[0,5]})
  say(a,"你","……？\n等等。\n我的那一勝呢？");say(a,"大師姐","哪一勝？")
  say(a,"你","剛才！二十一！");say(a,"大師姐","剛才那一局已經沒了。")
  say(a,"你","你不是說我贏一把就算我贏嗎？");say(a,"大師姐","你現在贏了嗎？")
  say(a,"你","……");say(a,"大師姐","築基七層。\n逆轉光陰。\n一場問劍裡，可以讓一局重新來過。")
  say(a,"你","這根本耍賴吧。");say(a,"大師姐","你終於懂了。")
 a.append({"kind":"end"});return a
